apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hello-argo-proj
  namespace: openshift-gitops
spec:
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
